### ISSUE TITLE
Impossible Wind Melody

### ISSUE THREAD

**Issue by kimimaru4000** [DontBaguMe/IoGR#4]
Randomizer stats:
```
"version: "3.1.0",
"seed: "928642626",
"goal": "Red Jewel Hunt",
"start_location": "Seaside Palace: Dark Space",
"logic": "Completable",
"difficulty": "Hard"
```
This is a no glitches run.

The Wind Melody is in the Jeweler's Mansion chest, but the goal is Red Jewel Hunt. This makes it impossible to complete Larai Cliff and beat Castoth, which in turn makes it impossible to complete Diamond Mine since Mine Key A is on the Gold Ship.

While the game itself is beatable, the logic for this seed is `Completable`, which should make it possible to obtain all items, including Mystic Statues.

**Comment by DontBaguMe** [comment]
Good point. We'll get that fixed in a future release.  Thank you.
