### ISSUE TITLE
Remove JK Rowling Quote from IOG Randomizer

### ISSUE THREAD

**Issue by githubwells** [DontBaguMe/IoGR#6]
The JKR Quote in the randomizer is offensive and it seems that you don't care about the community it offends at all based on the comments you've made. You pretend to support the community, but it doesn't seem like it at all. There is absolutely no need for the quote in there. You're supporting the wrong group and showing that you lack all respect for the trans and nb community by leaving it in and telling others who have asked you to remove it that you don't care and aren't willing to make that simple change. Please show an iota of respect and remove the quote.

**Comment by DontBaguMe** [comment]
I have created a branch called `no_death_quotes` that removes the death quote feature from the randomizer.  I will be sure to keep it up to date with the current production version moving forward.  I apologize for any offense, and I hope this is an acceptable compromise.

https://github.com/DontBaguMe/IoGR/tree/no_death_quotes

**Comment by githubwells** [comment]
The quotes are still there. They're still offensive and show that there's ill will toward the community by leaving them in. "Hey, I don't care about you enough about you to remove offensive and hurtful quotes because I really don't like the community" is what you're saying. It is an extremely simple solution to remove the quote, but, you'd rather be offensive toward a group of people because you like it and feels like you agree with that author's views. Using an excuse like another quote from another terrible person isn't a justification, either. Saying Mussolini's quote is there and you don't agree with those views isn't justification to anyone in the community. You're trying to justify your beliefs and give yourself an out in the situation. Instead, what you're doing is continuing to offend the community as a whole. It's not an acceptable compromise. You're not doing something helpful by branching it off because it's still there. You're still showing support for a TERF. You're still excluding trans and nb through your lack of action.

**Comment by DontBaguMe** [comment]
Since the quotes do not appear in plain text anywhere in the randomizer code, I'll post it here so people following this issue can decide for themselves whether it is offensive or not:

> "Death is just life's next big adventure."  -J. K. Rowling

**Comment by githubwells** [comment]
It is offensive because JKR is the one making the quote. The bigoted individual who hates a whole group of people because of who they are and nothing else. You side with her ideals by ignoring the concerns of those who used to play the randomizer. It is a simple fix to remove that from the randomizer, but you now officially add the quote here to further trigger people as a little sick joke. Do you get humor out of this? Do you think it's funny to attack the community? This is disgusting. 

The quote should be removed altogether.  There's no need for it, aside from intentionally trying to hurt people. It is a simple fix and you choose to ignore the fix. You choose to side with hate and bigotry. You choose to make the community exclusive instead of inclusive. No one else has chosen this. You have chosen to do this. You have shown your true colors here through this.

**Comment by neomatamune** [comment]
Bagu you can change the person you are quoting, I wrote this in a school work 2 years before JKR used it in a book so it won't be offensive to anyone if you quote me instead.
