### ISSUE TITLE
Seed not completable in logic

### ISSUE THREAD

**Issue by FujiiYakumo** [DontBaguMe/IoGR#7]
Hey, I've recently started trying out this randomizer and I think I ran into an issue with the most recent seed I tried, unless I've missed something like another way to reach the bottom of Babel Tower.  

I set up the game for four player's choice statues, with overworld shuffle and chaos logic modes.  I was only able to reach two mystic statues in logic.  I was able to finish the Great Wall and Mu.  

One of the map areas was Neil's Cottage, the Moon Tribe, and Dao.  The only way to enter that area that I know of is to have the Large Roast to reach Dao from the Native's Village, since you can't access Neil's cottage to play the memory melody to activate flight or access the Moon Tribe to use the Teapot to allow you to teleport back there from Sky Garden.  According to the spoiler log(which I attached), the roast was at the bottom of Babel Tower, and the only way that I'm aware of to reach the bottom of the tower is through Neil.  

I couldn't reach the Sky Garden boss because one crystal ball was at the end of Mt. Kress but the Mushroom Drops were in Dao, Babel Tower, and the Moon Tribe.  The Wind Melody for the Inca Ruins was in the Samlet check, but Ann had the second mine key and the Apple was in Dao.  Dao also had a hieroglyph tile, so I was unable to finish the Pyramid.  I was able to reach the sixth statue through the Jeweler's Mansion, but this was a normal difficulty seed and the readme says that Solid Arm should not be in logic unless it's Extreme.

[IoGR_v4.4.9_normal_DG4r_L(x)_S(s)_w_b_f_1319737881.txt](https://github.com/DontBaguMe/IoGR/files/11117277/IoGR_v4.4.9_normal_DG4r_L.x._S.s._w_b_f_1319737881.txt)

**Comment by neomatamune** [comment]
You can access Dao in logic by collecting 43 jewels and speaking to the jeweler, it will teleport you to the mansion and then you can exit it and get warped to Dao which is in logic.

**Comment by FujiiYakumo** [comment]
You know, I don't think I've ever actually exited the mansion that way, If I went in it was with the intention to finish it.  That's good to know, thanks.
